### ISSUE TITLE
Quantized model with FQ-ViT

### ISSUE THREAD

**Issue by uniqzheng** [megvii-research/FQ-ViT#10]
Hi!
   Thanks for your great work!
   Would you please provide the saved quantized model (ViT-base-patch16-384) with FQ-ViT?

**Comment by linyang-zhh** [comment]
Hi, @uniqzheng  
Sorry for that we have not provided quantized models and the interface for storing models.
However, you can refer to #1 and https://github.com/megvii-research/FQ-ViT/issues/15#issuecomment-1143544185, and just save the quantized models.

If you get other problems during above steps,  please feel free to reopen this issue.
