### ISSUE TITLE
A question about Log2Quantization when Activations or Weights equal to zeros

### ISSUE THREAD

**Issue by youdutaidi** [megvii-research/FQ-ViT#13]
I appreciate your Log2Quantization methods in FQ-Vit but I have a questions that:
when activations and weights equal to zero, we can not log2(0), and when they are negtive numbers ,we can not opreate it , either. But it seems in the code it did not notice that problem.

**Comment by lz02k** [comment]
Actually, the "Log2Quantization" method is only used for Softmax activation with a value range of (0, 1).
