### ISSUE TITLE
ViT-B input quant=False 测试问题

### ISSUE THREAD

**Issue by tpoisonooo** [megvii-research/FQ-ViT#17]
我看源码里 ViT-B input_quant=False 。
想问您那边 input_quant=True 的话，精度预计是多少？

**Comment by linyang-zhh** [comment]
如该行 [link](https://github.com/megvii-research/FQ-ViT/blob/54ddb6beee2ab239aa8526f64a5308d2fe864d91/test_quant.py#L88), ViT系列模型对输入做的是layer-wise的norm，故其经过预处理后依然是一个int8可以表示的数据，所以实际上无须增加input_quant。

基于上面的原因，如果设为True，精度将几乎不变
