### ISSUE TITLE
请问对于2/4 bits是否可扩展？

### ISSUE THREAD

**Issue by Facatt** [megvii-research/FQ-ViT#24]
您好，非常具有启发性的工作！

有一个问题：是否可BIT_TYPE_LIST添加新的：BitType(2, True, 'int2'), BitType(2, False, 'uint2'), BitType(4, True, 'int4')，来尝试量化某些模块到更低比特？

感谢！

**Comment by linyang-zhh** [comment]
感谢对我们工作的认可！
拓展BIT_TYPE_LIST是可以的！欢迎尝试～
