### ISSUE TITLE
when i use the method to do object detection, how to apply the calibration step for that detector in MMDet framework？

### ISSUE THREAD

**Issue by Wuyy-fairy** [megvii-research/FQ-ViT#27]
Good jobs！
I try to use the code to realize the object detection,but I can't understand the step "apply the calibration step for that detector in MMDet framework",can you give me more detailed instructions?thanks very much!

**Comment by PeiqinSun** [comment]
We will release an mm-detection example with our new quantization tools. https://github.com/megvii-research/Sparsebit/
You can raise issue in sparsebit.
