### ISSUE TITLE
How to visualize the Figure3?

### ISSUE THREAD

**Issue by YoloEliwa** [megvii-research/FQ-ViT#28]
Hello,
Thanks for this amazing work!
I want to know how to obtain distribution like Figure3. Can you share the visualization code with me?
I am looking forward to your reply!

**Comment by PeiqinSun** [comment]
1, get the attention-map outputs of some samples
2, draw data bins(i.e. 2048 bins) in figure use the pyplot

**Comment by YoloEliwa** [comment]
Thanks for your reply! 
I want to know how to set the x-axis like Figure3？And, how many samples you used？

**Comment by linyang-zhh** [comment]
> Thanks for your reply!
> I want to know how to set the x-axis like Figure3？And, how many samples you used？

1. use `matplotlib` with `plt.xscale('log')`
2. We use 100 random samples on ImageNet and we believe that the number of samples has little influence on that distribution.
