### ISSUE TITLE
tensorrt

### ISSUE THREAD

**Issue by shuyuan-wang** [megvii-research/FQ-ViT#29]
swin transformer量化后在tensorrt上latency怎么样，和fp32的比？

**Comment by linyang-zhh** [comment]
Sorry. We didn't carry out and release those experiments about hardware and latency.
You can find more information about the latency on tensorRT or other platforms in [Sparsebit](https://github.com/megvii-research/Sparsebit) and [MMDeploy](https://github.com/open-mmlab/mmdeploy).
