### ISSUE TITLE
Confused about Fake Quantization

### ISSUE THREAD

**Issue by jhss** [megvii-research/FQ-ViT#30]
In the [issue](https://github.com/megvii-research/FQ-ViT/issues/6#issuecomment-1030876219), you said that quant and dequant is necessary step for quantization.

You recommended to reference the Figure 6 in the [paper](https://arxiv.org/pdf/2103.13630.pdf).

![1](https://user-images.githubusercontent.com/8586144/214217931-c50b5fc0-6545-454f-b4ca-eb7d37fe12d1.PNG)

What I don't understand is that fake quantization is actually FP32 matrix multiplication as above figure according to your recommended paper. However, in your paper, you said that your model is Fully-Quantized Vision Transfomer (FQ-VIT), which seems to contradict that you actually use FP32 matrix multiplication except LayerNorm and Softmax.

Also, Fake quantization is usually used during quantization-aware training. However, your method is post-training quantization, so I don't understand why dequant is necessary step for post-training quantization. I looked at the other paper code, but there was no place to use dequant during post-training quantization.

I appreciate if you answer the question.

**Comment by linyang-zhh** [comment]
We use FakeQuantization to rapidly develop our algorithm, and our FakeQuantization and the integer-only inference are numerically equivalent.

**Comment by gihwan-kim** [comment]
> We use FakeQuantization to rapidly develop our algorithm, and our FakeQuantization and the integer-only inference are numerically equivalent.

I agree to use FakeQuantization to rapidly develop algorithm. But.
Did you check at the integer MatrixMultiplication is also equivalent by yourself ?
I printed Query and Key tensor before MatMul, datatype was floating point that means floating point arithmetic. I thnik it will not gurantee integer MatMul at the real inference level.
