### ISSUE TITLE
Inference speed of quantized model is lower than normal model

### ISSUE THREAD

**Issue by jhss** [megvii-research/FQ-ViT#32]
**- Fully Quantized ViT**

![fq1](https://user-images.githubusercontent.com/8586144/215042892-d4508fea-85d6-493b-874f-39000b84111e.PNG)
![fq](https://user-images.githubusercontent.com/8586144/215042901-39d53b15-ce4d-4f54-a201-2ad528f5d949.PNG)

**- Normal ViT**

![normal](https://user-images.githubusercontent.com/8586144/215042942-2f5d6e30-5754-456f-8fe8-743e3167b1bd.PNG)
![normal2](https://user-images.githubusercontent.com/8586144/215042949-8ce9acaf-eca2-4990-a7c9-d5970a295126.PNG)

I used Nvidia A10 to train the FQ-VIT. 

I thought that the inference speed of quantized model is much faster than original one, but the result was opposite.

Is there any reason why the inference speed of quantized model is much slower than normal one?

**Comment by Ther-nullptr** [comment]
Because this project only *simulates* the process of quantitative inference, and quantitative inference *in the numerical results* of the same, but not really with int 8 type data calculation, plus the project *did not optimize the arithmetic for hardware*, so the speed did not become faster is normal.

**Comment by jhss** [comment]
Thank you for answering.

I wonder what the purpose of simulated quantization is if there is no speed increase.

**Comment by Ther-nullptr** [comment]
the model will finally set up on a edge equipment, which will only support int calculation use TersorRT or other toolkits. but int calculation is meaningless  on pytorch because the
operator in pytorch doesn't support int calculation.

**Comment by jhss** [comment]
Then, if i convert the model in this repository to tensorRT, the inference speed can be accelerated?

**Comment by Ther-nullptr** [comment]
yeah, but you may write some operator to adapt to your hardware.

**Comment by jhss** [comment]
Now I understand. Thank you very much!

Have a good day :)
