### ISSUE TITLE
QIntLayerNorm 讲 self.mode = 'int'

### ISSUE THREAD

**Issue by PeiyanFlying** [megvii-research/FQ-ViT#36]
您好，请问我将 QIntLayerNorm 中的 self.mode 设置成了 ‘int’。但是，程序报错，请问可能是哪里出现的问题呢？麻烦了！谢谢您！

**Comment by PeiyanFlying** [comment]
![image](https://user-images.githubusercontent.com/45463777/230818788-6b745506-9ce9-49e8-8e14-96f0aeeb9a40.png)

**Comment by linyang-zhh** [comment]
Please keep `QIntLayerNorm` in `ln` mode during the calibration step.
After the calibration, call `model.model_quant()` and it will set `QIntLayerNorm` to `int` mode.

**Comment by PeiyanFlying** [comment]
Ok, sure! That works!
Sorry about another question. I read the code and the function 'def get_MN(self, x)' in QIntLayerNorm. I am a little confused. What does the M and N represent? Does the N represent the 'a' in the Equation (8)? And the function 'def get_MN(self, x)' is the Equantion (11) ?
![image](https://user-images.githubusercontent.com/45463777/230828231-f07f96c5-97b3-4611-908c-cacc7792c45c.png)

![image](https://user-images.githubusercontent.com/45463777/230827999-6a05dadd-2aab-4e0f-a94e-9f67d932ac15.png)

I appreciate your help. Thanks so much!

**Comment by linyang-zhh** [comment]
No. They are in the Eq. (31) - (32) on the appendix of the paper.

**Comment by PeiyanFlying** [comment]
Ok, sure. Many thanks for your help!
