### ISSUE TITLE
Some Questions about the Quantized Inference

### ISSUE THREAD

**Issue by PeiyanFlying** [megvii-research/FQ-ViT#37]
Hi, I'm not clear about the Power-of-Two Factor.
I see the equation (23). How do you get the parameter 'a'? 
![image](https://user-images.githubusercontent.com/45463777/231293158-e20db3b2-fb8e-4d7b-8ae6-e295302af1be.png)
And the corresponding code is this part?
![image](https://user-images.githubusercontent.com/45463777/231293530-32db13e6-13fe-4f67-825b-7f5f70d7fbc8.png)
Thanks for your helping!

**Comment by linyang-zhh** [comment]
Here [link](https://github.com/megvii-research/FQ-ViT/blob/5daf5915c715dc21d6afcd64e661652030e640ab/models/ptq/observer/ptf.py#L64)
