### ISSUE TITLE
为什么BaseQuantizer的forward要反量化？

### ISSUE THREAD

**Issue by zouzihan3** [megvii-research/FQ-ViT#43]
```python
def forward(self, inputs):
outputs = self.quant(inputs)
outputs = self.dequantize(outputs)
return outputs
```
这里在运行前，将量化好的整数又搞回去了。我从事的是IC设计方向，所以如果这么干又何来量化一说？不太理解为什么这么操作，请教一下作者如果希望导出整数权重并执行如何处理。

**Comment by zouzihan3** [comment]
此外，我尝试注释掉反量化部分内容，程序的准确率直接爆掉了。

**Comment by HJQjob** [comment]
Hello, I am also engaged in research on neural network acceleration. May I ask if your question has been resolved.
How to achieve acceleration when deployed on hardware, which is different from analog quantization inference in PyTorch.
